{
  "swagger": "2.0",
  "info": {
    "contact": {
      "name": "Selling Partner API Developer Support",
      "url": "https://sellercentral.amazon.com/gp/mws/contactus.html"
    },
    "description": "The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.",
    "license": {
      "name": "Apache License 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0"
    },
    "title": "The Selling Partner API for FBA inbound operations.",
    "version": "2024-03-20"
  },
  "host": "sellingpartnerapi-na.amazon.com",
  "schemes": [
    "https"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "x-components": {},
  "paths": {
    "/inbound/fba/2024-03-20/inboundPlans": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateInboundPlanRequest"
            },
            "description": "The body of the request to `createInboundPlan`."
          }
        ],
        "responses": {
          "202": {
            "description": "CreateInboundPlan 202 response",
            "schema": {
              "$ref": "#/definitions/CreateInboundPlanResponse"
            },
            "x-amzn-api-sandbox": {
              "static": [
                {
                  "request": {
                    "parameters": {
                      "body": {
                        "value": {
                          "name": "FBA (03/20/2024, 12:01 PM)",
                          "sourceAddress": {
                            "name": "name",
                            "companyName": "Acme",
                            "addressLine1": "123 example street",
                            "addressLine2": "Unit 102",
                            "city": "Toronto",
                            "countryCode": "CA",
                            "stateOrProvinceCode": "ON",
                            "postalCode": "M1M1M1",
                            "phoneNumber": "1234567890",
                            "email": "email@email.com"
                          },
                          "destinationMarketplaces": [
                            "A2EUQ1WTGCTBG2"
                          ],
                          "items": [
                            {
                              "msku": "msku",
                              "prepOwner": "AMAZON",
                              "labelOwner": "AMAZON",
                              "quantity": 2,
                              "expiration": "2024-01-01",
                              "manufacturingLotCode": "lotCode"
                            }
                          ]
                        }
                      }
                    }
                  },
                  "response": {
                    "inboundPlanId": "wf1234abcd-1234-abcd-5678-1234abcd5678",
                    "operationId": "1234abcd-1234-abcd-5678-1234abcd5678"
                  }
                },
                {
                  "request": {
                    "parameters": {
                      "body": {
                        "value": {
                          "name": "FBA (03/20/2024, 12:01 PM)",
                          "sourceAddress": {
                            "name": "name",
                            "companyName": "TheCompany",
                            "addressLine1": "1111 street name",
                            "addressLine2": "Apartment 12B",
                            "city": "Ann Arbor",
                            "districtOrCounty": "Washtenaw",
                            "stateOrProvinceCode": "MI",
                            "postalCode": "11564",
                            "countryCode": "US",
                            "phoneNumber": "1234567890",
                            "email": "email@email.com"
                          },
                          "destinationMarketplaces": [
                            "BADATVPDKIKX0DER"
                          ],
                          "items": [
                            {
                              "msku": "msku",
                              "prepOwner": "AMAZON",
                              "labelOwner": "AMAZON",
                              "quantity": 2,
                              "expiration": "2024-01-01",
                              "manufacturingLotCode": "lotCode"
                            }
                          ]
                        }
                      }
                    }
                  },
                  "response": {
                    "inboundPlanId": "wf1234abcd-1234-abcd-5678-1234abcd5678",
                    "operationId": "1234abcd-1234-abcd-5678-1234abcd5678"
                  }
                }
              ]
            },
            "headers": {
              "x-amzn-RequestId": {
                "description": "Unique request reference identifier.",
                "type": "string"
              },
              "x-amzn-RateLimit-Limit": {
                "description": "Your rate limit (requests per second) for this operation.",
                "type": "string"
              }
            }
          },
          "400": {
            "description": "Request has missing or invalid parameters and cannot be parsed.",
            "schema": {
              "$ref": "#/definitions/ErrorList"
            },
            "x-amzn-api-sandbox": {
              "static": [
                {
                  "request": {
                    "parameters": {
                      "body": {
                        "value": {
                          "name": "FBA (03/20/2024, 12:01 PM)",
                          "sourceAddress": {
                            "name": "name",
                            "companyName": "Acme",
                            "addressLine1": "123 example street",
                            "addressLine2": "Unit 102",
                            "city": "Toronto",
                            "countryCode": "CA",
                            "stateOrProvinceCode": "ON",
                            "postalCode": "M1M1M1",
                            "phoneNumber": "1234567890",
                            "email": "email@email.com"
                          },
                          "destinationMarketplaces": [
                            "badMarketplace"
                          ],
                          "items": [
                            {
                              "msku": "msku",
                              "prepOwner": "AMAZON",
                              "labelOwner": "AMAZON",
                              "quantity": 2,
                              "expiration": "2024-01-01",
                              "manufacturingLotCode": "lotCode"
                            }
                          ]
                        }
                      }
                    }
                  },
                  "response": {
                    "errors": [
                      {
                        "code": "BadRequest",
                        "message": "Invalid destinationMarketplace provided."
                      }
                    ]
                  }
                },
                {
                  "request": {
                    "parameters": {
                      "body": {
                        "value": {
                          "name": "FBA (03/20/2024, 12:01 PM)",
                          "sourceAddress": {
                            "name": "name",
                            "companyName": "TheCompany",
                            "addressLine1": "1111 street name",
                            "addressLine2": "Apartment 12B",
                            "city": "Ann Arbor",
                            "districtOrCounty": "Washtenaw",
                            "stateOrProvinceCode": "MI",
                            "postalCode": "11564",
                            "countryCode": "US",
                            "phoneNumber": "1234567890",
                            "email": "email@email.com"
                          },
                          "destinationMarketplaces": [
                            "badMarketplace"
                          ],
                          "items": [
                            {
                              "msku": "msku",
                              "prepOwner": "AMAZON",
                              "labelOwner": "AMAZON",
                              "quantity": 2,
                              "expiration": "2024-01-01",
                              "manufacturingLotCode": "lotCode"
                            }
                          ]
                        }
                      }
                    }
                  },
                  "response": {
                    "errors": [
                      {
                        "code": "BadRequest",
                        "message": "Invalid destinationMarketplace provided."
                      }
                    ]
                  }
                }
              ]
            },
            "headers": {
              "x-amzn-RequestId": {
                "description": "Unique request reference identifier.",
                "type": "string"
              },
              "x-amzn-RateLimit-Limit": {
                "description": "Your rate limit (requests per second) for this operation.",
                "type": "string"
              }
            }
          },
          "404": {
            "description": "The resource specified does not exist.",
            "schema": {
              "$ref": "#/definitions/ErrorList"
            },
            "headers": {
              "x-amzn-RequestId": {
                "description": "Unique request reference identifier.",
                "type": "string"
              },
              "x-amzn-RateLimit-Limit": {
                "description": "Your rate limit (requests per second) for this operation.",
                "type": "string"
              }
            }
          },
          "500": {
            "description": "An unexpected condition occurred that prevented the server from fulfilling the request.",
            "schema": {
              "$ref": "#/definitions/ErrorList"
            },
            "headers": {
              "x-amzn-RequestId": {
                "description": "Unique request reference identifier.",
                "type": "string"
              }
            }
          },
          "403": {
            "description": "Indicates that access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature.",
            "schema": {
              "$ref": "#/definitions/ErrorList"
            },
            "headers": {
              "x-amzn-RequestId": {
                "description": "Unique request reference identifier.",
                "type": "string"
              }
            }
          },
          "413": {
            "description": "The request size exceeded the maximum accepted size.",
            "schema": {
              "$ref": "#/definitions/ErrorList"
            },
            "headers": {
              "x-amzn-RequestId": {
                "description": "Unique request reference identifier.",
                "type": "string"
              }
            }
          },
          "415": {
            "description": "The request payload is in an unsupported format.",
            "schema": {
              "$ref": "#/definitions/ErrorList"
            },
            "headers": {
              "x-amzn-RequestId": {
                "description": "Unique request reference identifier.",
                "type": "string"
              }
            }
          },
          "429": {
            "description": "The frequency of requests was greater than allowed.",
            "schema": {
              "$ref": "#/definitions/ErrorList"
            },
            "headers": {
              "x-amzn-RequestId": {
                "description": "Unique request reference identifier.",
                "type": "string"
              }
            }
          },
          "503": {
            "description": "Temporary overloading or maintenance of the server.",
            "schema": {
              "$ref": "#/definitions/ErrorList"
            },
            "headers": {
              "x-amzn-RequestId": {
                "description": "Unique request reference identifier.",
                "type": "string"
              }
            }
          }
        },
        "tags": [
          "fbaInbound"
        ],
        "description": "Creates an inbound plan. An inbound plan contains all the necessary information to send shipments into Amazon's fufillment network.",
        "operationId": "createInboundPlan"
      }
    }
  },
  "definitions": {
    "CreateInboundPlanResponse": {
      "description": "The `createInboundPlan` response.",
      "properties": {
        "inboundPlanId": {
          "description": "Identifier of an inbound plan.",
          "maxLength": 38,
          "minLength": 38,
          "pattern": "^[a-zA-Z0-9-]*$",
          "type": "string"
        },
        "operationId": {
          "description": "UUID for the given operation.",
          "maxLength": 38,
          "minLength": 36,
          "pattern": "^[a-zA-Z0-9-]*$",
          "type": "string"
        }
      },
      "required": [
        "inboundPlanId",
        "operationId"
      ],
      "type": "object"
    },
    "AddressInput": {
      "description": "Specific details to identify a place.",
      "properties": {
        "addressLine1": {
          "description": "Street address information.",
          "maxLength": 180,
          "minLength": 1,
          "type": "string"
        },
        "addressLine2": {
          "description": "Additional street address information.",
          "maxLength": 60,
          "minLength": 1,
          "type": "string"
        },
        "city": {
          "description": "The city.",
          "maxLength": 30,
          "minLength": 1,
          "type": "string"
        },
        "companyName": {
          "description": "The name of the business.",
          "maxLength": 50,
          "minLength": 1,
          "type": "string"
        },
        "countryCode": {
          "description": "The country code in two-character ISO 3166-1 alpha-2 format.",
          "maxLength": 2,
          "minLength": 2,
          "pattern": "^[A-Z]{2}$",
          "type": "string"
        },
        "districtOrCounty": {
          "description": "The district or county.",
          "maxLength": 50,
          "minLength": 1,
          "type": "string"
        },
        "email": {
          "description": "The email address.",
          "maxLength": 1024,
          "minLength": 1,
          "type": "string"
        },
        "name": {
          "description": "The name of the individual who is the primary contact.",
          "maxLength": 50,
          "minLength": 1,
          "type": "string"
        },
        "phoneNumber": {
          "description": "The phone number.",
          "maxLength": 20,
          "minLength": 1,
          "type": "string"
        },
        "postalCode": {
          "description": "The postal code.",
          "maxLength": 32,
          "minLength": 1,
          "type": "string"
        },
        "stateOrProvinceCode": {
          "description": "The state or province code.",
          "maxLength": 64,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "addressLine1",
        "city",
        "countryCode",
        "name",
        "phoneNumber",
        "postalCode"
      ],
      "type": "object",
      "example": {
        "addressLine1": "123 example street",
        "addressLine2": "Floor 19",
        "city": "Toronto",
        "companyName": "Acme",
        "countryCode": "CA",
        "email": "email@email.com",
        "name": "name",
        "phoneNumber": "1234567890",
        "postalCode": "M1M1M1",
        "stateOrProvinceCode": "ON"
      }
    },
    "ErrorList": {
      "description": "A list of error responses returned when a request is unsuccessful.",
      "properties": {
        "errors": {
          "description": "List of errors.",
          "items": {
            "$ref": "#/definitions/Error"
          },
          "type": "array"
        }
      },
      "required": [
        "errors"
      ],
      "type": "object"
    },
    "Error": {
      "description": "Error object containing information about what went wrong.",
      "properties": {
        "code": {
          "description": "An error code that identifies the type of error that occurred.",
          "maxLength": 256,
          "minLength": 1,
          "type": "string"
        },
        "details": {
          "description": "Additional details that can help the caller understand or fix the issue.",
          "maxLength": 8192,
          "minLength": 0,
          "type": "string"
        },
        "message": {
          "description": "A message that describes the error condition.",
          "maxLength": 2048,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "code",
        "message"
      ],
      "type": "object",
      "example": {
        "code": "FBA_ERROR_001",
        "details": "The shipment is in a status that does not allow it to be edited.",
        "message": "Invalid Request"
      }
    },
    "PrepOwner": {
      "description": "The owner of the preparations, if special preparations are required.",
      "enum": [
        "AMAZON",
        "SELLER",
        "NONE"
      ],
      "type": "string",
      "x-docgen-enum-table-extension": [
        {
          "value": "AMAZON",
          "description": "Amazon provides the information."
        },
        {
          "value": "SELLER",
          "description": "The seller provides the information."
        },
        {
          "value": "NONE",
          "description": "No owner is required for the preparations."
        }
      ]
    },
    "ItemInput": {
      "description": "Defines an item's input parameters.",
      "properties": {
        "expiration": {
          "description": "The expiration date of the MSKU. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) datetime format with pattern `YYYY-MM-DD`. Items with the same MSKU but different expiration dates cannot go into the same box.",
          "pattern": "^([0-9]{4})-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])$",
          "type": "string"
        },
        "labelOwner": {
          "$ref": "#/definitions/LabelOwner"
        },
        "manufacturingLotCode": {
          "description": "The manufacturing lot code.",
          "maxLength": 256,
          "minLength": 1,
          "type": "string"
        },
        "msku": {
          "description": "The merchant SKU, a merchant-supplied identifier of a specific SKU.",
          "maxLength": 255,
          "minLength": 1,
          "type": "string"
        },
        "prepOwner": {
          "$ref": "#/definitions/PrepOwner"
        },
        "quantity": {
          "description": "The number of units of the specified MSKU that will be shipped.",
          "maximum": 500000,
          "minimum": 1,
          "type": "integer"
        }
      },
      "required": [
        "labelOwner",
        "msku",
        "prepOwner",
        "quantity"
      ],
      "type": "object",
      "example": {
        "expiration": "2024-01-01",
        "labelOwner": "AMAZON",
        "manufacturingLotCode": "manufacturingLotCode",
        "msku": "Sunglasses",
        "prepOwner": "AMAZON",
        "quantity": 10
      }
    },
    "LabelOwner": {
      "description": "Specifies who will label the items. Options include `AMAZON`, `SELLER` or `NONE`.",
      "enum": [
        "AMAZON",
        "SELLER",
        "NONE"
      ],
      "type": "string",
      "x-docgen-enum-table-extension": [
        {
          "value": "AMAZON",
          "description": "Amazon provides the information."
        },
        {
          "value": "SELLER",
          "description": "Seller provides the information."
        },
        {
          "value": "NONE",
          "description": "No owner is required for the labelling."
        }
      ]
    },
    "CreateInboundPlanRequest": {
      "description": "The `createInboundPlan` request.",
      "properties": {
        "destinationMarketplaces": {
          "description": "Marketplaces where the items need to be shipped to. Currently only one marketplace can be selected in this request.",
          "items": {
            "description": "The Marketplace ID. For a list of possible values, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids).",
            "maxLength": 20,
            "minLength": 1,
            "type": "string"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "items": {
          "description": "Items included in this plan.",
          "items": {
            "$ref": "#/definitions/ItemInput"
          },
          "maxItems": 2000,
          "minItems": 1,
          "type": "array"
        },
        "name": {
          "description": "Name for the Inbound Plan. If one isn't provided, a default name will be provided.",
          "maxLength": 40,
          "minLength": 1,
          "type": "string"
        },
        "sourceAddress": {
          "$ref": "#/definitions/AddressInput"
        }
      },
      "required": [
        "destinationMarketplaces",
        "items",
        "sourceAddress"
      ],
      "type": "object",
      "example": {
        "destinationMarketplaces": [
          "ATVPDKIKX0DER"
        ],
        "items": [
          {
            "expiration": "2024-01-01",
            "labelOwner": "AMAZON",
            "manufacturingLotCode": "manufacturingLotCode",
            "msku": "Sunglasses",
            "prepOwner": "AMAZON",
            "quantity": 10
          }
        ],
        "name": "My inbound plan",
        "sourceAddress": {
          "addressLine1": "123 example street",
          "addressLine2": "Floor 19",
          "city": "Toronto",
          "companyName": "Acme",
          "countryCode": "CA",
          "email": "email@email.com",
          "name": "name",
          "phoneNumber": "1234567890",
          "postalCode": "M1M1M1",
          "stateOrProvinceCode": "ON"
        }
      }
    }
  }
}
